[2025-02-20 23:45:21,414:INFO:main:Welcome !!]
[2025-02-21 20:17:42,209:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-21 20:17:42,211:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-21 20:17:48,263:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-21 20:17:48,264:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-21 20:23:36,482:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-21 20:23:36,484:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-21 20:28:24,721:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-21 20:28:24,758:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-21 20:28:24,761:INFO:common:created directory at: artifacts]
[2025-02-21 20:28:24,764:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-21 20:31:00,930:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-21 20:31:00,932:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-21 20:31:00,935:INFO:common:created directory at: artifacts]
[2025-02-21 20:31:00,937:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-21 20:32:22,595:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-21 20:32:22,599:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-21 20:32:22,602:INFO:common:created directory at: artifacts]
[2025-02-21 20:32:22,604:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-21 20:32:22,606:INFO:2312406266:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-21 20:34:41,587:INFO:2312406266:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-21 21:11:40,548:INFO:main: stage Data Ingestion stage  started]
[2025-02-21 21:11:40,550:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-21 21:11:40,551:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-21 21:11:40,552:INFO:common:created directory at: artifacts]
[2025-02-21 21:11:40,553:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-21 21:11:40,554:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-21 21:12:14,068:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-21 21:12:14,648:INFO:main:Stage Data Ingestion stage completed]
[2025-02-22 18:33:27,841:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 18:33:27,853:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 18:33:27,855:INFO:common:created directory at: artifacts]
[2025-02-22 18:33:27,855:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-22 18:34:22,558:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 18:34:22,562:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 18:34:22,563:INFO:common:created directory at: artifacts]
[2025-02-22 18:34:22,563:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-22 18:35:22,300:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 18:35:22,304:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 18:35:22,305:INFO:common:created directory at: artifacts]
[2025-02-22 18:35:22,306:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-22 18:38:56,656:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 18:38:56,663:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 18:38:56,664:INFO:common:created directory at: artifacts]
[2025-02-22 18:38:56,665:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-22 18:39:20,594:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 18:39:20,600:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 18:39:20,602:INFO:common:created directory at: artifacts]
[2025-02-22 18:39:20,603:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-22 18:39:45,995:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 18:39:46,002:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 18:39:46,005:INFO:common:created directory at: artifacts]
[2025-02-22 18:39:46,006:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-22 18:41:47,602:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 18:41:47,609:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 18:41:47,611:INFO:common:created directory at: artifacts]
[2025-02-22 18:41:47,613:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-22 18:42:16,544:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 18:42:16,549:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 18:42:16,552:INFO:common:created directory at: artifacts]
[2025-02-22 18:42:16,554:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-22 18:42:51,601:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 18:42:51,606:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 18:42:51,608:INFO:common:created directory at: artifacts]
[2025-02-22 18:42:51,609:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-22 18:44:06,926:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 18:44:06,932:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 18:44:06,935:INFO:common:created directory at: artifacts]
[2025-02-22 18:44:06,937:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-22 18:44:20,684:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 18:44:20,691:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 18:44:20,693:INFO:common:created directory at: artifacts]
[2025-02-22 18:44:20,696:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-22 18:47:10,091:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 18:47:10,098:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 18:47:10,102:INFO:common:created directory at: artifacts]
[2025-02-22 18:47:10,104:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-22 18:48:42,976:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 18:48:42,983:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 18:48:42,985:INFO:common:created directory at: artifacts]
[2025-02-22 18:48:42,987:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-22 18:51:31,719:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 18:51:31,727:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 18:51:31,729:INFO:common:created directory at: artifacts]
[2025-02-22 18:51:31,731:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-22 18:51:57,270:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-22 20:08:42,672:INFO:main: stage Data Ingestion stage  started]
[2025-02-22 20:08:42,698:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 20:08:42,722:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 20:08:42,723:INFO:common:created directory at: artifacts]
[2025-02-22 20:08:42,723:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-22 20:08:42,723:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-22 20:09:04,611:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-22 20:09:04,978:INFO:main:Stage Data Ingestion stage completed]
[2025-02-22 20:09:04,978:INFO:main: stage Prepare base model  started]
[2025-02-22 20:09:04,979:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 20:09:04,982:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 20:09:04,982:INFO:common:created directory at: artifacts]
[2025-02-22 20:09:04,983:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-22 20:09:05,303:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-22 20:09:05,473:INFO:main:Stage Prepare base model completed]
[2025-02-22 21:16:55,492:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 21:16:55,495:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 21:16:55,497:INFO:common:created directory at: artifacts]
[2025-02-22 21:17:17,977:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 21:17:17,982:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 21:17:17,983:INFO:common:created directory at: artifacts]
[2025-02-22 21:17:17,985:INFO:common:created directory at: artifacts\training]
[2025-02-22 21:18:28,556:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 21:18:28,561:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 21:18:28,563:INFO:common:created directory at: artifacts]
[2025-02-22 21:18:28,564:INFO:common:created directory at: artifacts\training]
[2025-02-22 21:19:15,278:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 21:19:15,281:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 21:19:15,282:INFO:common:created directory at: artifacts]
[2025-02-22 21:19:15,283:INFO:common:created directory at: artifacts\training]
[2025-02-22 22:05:40,744:INFO:main: stage Data Ingestion stage  started]
[2025-02-22 22:05:40,747:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 22:05:40,800:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 22:05:40,802:INFO:common:created directory at: artifacts]
[2025-02-22 22:05:40,806:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-22 22:05:40,811:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-22 22:07:19,374:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-22 22:07:20,150:INFO:main:Stage Data Ingestion stage completed]
[2025-02-22 22:07:20,151:INFO:main: stage Prepare base model  started]
[2025-02-22 22:07:20,154:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 22:07:20,157:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 22:07:20,157:INFO:common:created directory at: artifacts]
[2025-02-22 22:07:20,158:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-22 22:07:20,736:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-22 22:07:21,041:INFO:main:Stage Prepare base model completed]
[2025-02-22 22:07:21,042:INFO:main: stage Training  started]
[2025-02-22 22:07:21,044:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 22:07:21,048:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 22:07:21,049:INFO:common:created directory at: artifacts]
[2025-02-22 22:07:21,050:INFO:common:created directory at: artifacts\training]
[2025-02-22 22:08:25,958:INFO:main:Stage Training completed]
[2025-02-22 23:28:33,938:INFO:main: stage Data Ingestion stage  started]
[2025-02-22 23:28:33,944:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 23:28:33,960:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 23:28:33,964:INFO:common:created directory at: artifacts]
[2025-02-22 23:28:33,966:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-22 23:28:33,968:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-22 23:28:46,025:ERROR:main:HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?/export=download&id=1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000180B6570B50>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)"))]
Traceback (most recent call last):
  File "C:\projet\Kideny_Disease_Classification\my_nzw_kideny\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "C:\projet\Kideny_Disease_Classification\my_nzw_kideny\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\projet\Kideny_Disease_Classification\my_nzw_kideny\lib\socket.py", line 967, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\projet\Kideny_Disease_Classification\my_nzw_kideny\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "C:\projet\Kideny_Disease_Classification\my_nzw_kideny\lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\projet\Kideny_Disease_Classification\my_nzw_kideny\lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "C:\projet\Kideny_Disease_Classification\my_nzw_kideny\lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "C:\projet\Kideny_Disease_Classification\my_nzw_kideny\lib\site-packages\urllib3\connection.py", line 704, in connect
    self.sock = sock = self._new_conn()
  File "C:\projet\Kideny_Disease_Classification\my_nzw_kideny\lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x00000180B6570B50>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\projet\Kideny_Disease_Classification\my_nzw_kideny\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\projet\Kideny_Disease_Classification\my_nzw_kideny\lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "C:\projet\Kideny_Disease_Classification\my_nzw_kideny\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?/export=download&id=1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000180B6570B50>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\projet\Kideny_Disease_Classification\main.py", line 10, in <module>
    obj.main()
  File "c:\projet\kideny_disease_classification\src\cnnClassifier\pipeline\stage_01_data_Ingestion.py", line 14, in main
    data_ingestion.download_file()
  File "c:\projet\kideny_disease_classification\src\cnnClassifier\components\data_ingestion.py", line 27, in download_file
    raise e
  File "c:\projet\kideny_disease_classification\src\cnnClassifier\components\data_ingestion.py", line 22, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "C:\projet\Kideny_Disease_Classification\my_nzw_kideny\lib\site-packages\gdown\download.py", line 202, in download
    res = sess.get(url, stream=True, verify=verify)
  File "C:\projet\Kideny_Disease_Classification\my_nzw_kideny\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "C:\projet\Kideny_Disease_Classification\my_nzw_kideny\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\projet\Kideny_Disease_Classification\my_nzw_kideny\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\projet\Kideny_Disease_Classification\my_nzw_kideny\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?/export=download&id=1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000180B6570B50>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)"))
[2025-02-22 23:29:40,753:INFO:main: stage Data Ingestion stage  started]
[2025-02-22 23:29:40,756:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 23:29:40,760:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 23:29:40,760:INFO:common:created directory at: artifacts]
[2025-02-22 23:29:40,761:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-22 23:29:40,763:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-22 23:33:00,196:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-22 23:33:01,021:INFO:main:Stage Data Ingestion stage completed]
[2025-02-22 23:33:01,022:INFO:main: stage Prepare base model  started]
[2025-02-22 23:33:01,025:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 23:33:01,032:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 23:33:01,034:INFO:common:created directory at: artifacts]
[2025-02-22 23:33:01,035:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-22 23:33:01,762:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-22 23:33:02,017:INFO:main:Stage Prepare base model completed]
[2025-02-22 23:33:02,018:INFO:main: stage Training  started]
[2025-02-22 23:33:02,020:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-22 23:33:02,025:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-22 23:33:02,026:INFO:common:created directory at: artifacts]
[2025-02-22 23:33:02,027:INFO:common:created directory at: artifacts\training]
[2025-02-23 02:02:47,230:INFO:main:Stage Training completed]
[2025-02-23 02:24:24,351:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-23 02:24:24,362:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-23 02:24:24,363:INFO:common:created directory at: artifacts]
[2025-02-23 02:25:45,422:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-23 02:25:45,425:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-23 02:25:45,426:INFO:common:created directory at: artifacts]
[2025-02-23 02:25:54,141:INFO:common:json file saved at:scores.json]
[2025-02-23 02:25:57,262:WARNING:save:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-02-23 02:25:57,737:INFO:builder_impl:Assets written to: C:\Users\RYM\AppData\Local\Temp\tmpr5_9nksw\model\data\model\assets]
[2025-02-23 02:33:29,695:WARNING:connectionpool:Retrying (Retry(total=4, connect=5, read=5, redirect=5, status=5)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /RymTangour/Kideny_Disease_Classification.mlflow/api/2.0/mlflow-artifacts/artifacts/a86bfbcd9098411f95a8c8439f64c854/5b8a56cd847a4ae0a4a249cf9779e945/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2025-02-23 02:52:01,704:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-23 02:52:01,710:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-23 02:52:01,712:INFO:common:created directory at: artifacts]
[2025-02-23 02:52:26,547:INFO:common:json file saved at:scores.json]
[2025-02-23 02:52:30,779:WARNING:save:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-02-23 02:52:31,540:INFO:builder_impl:Assets written to: C:\Users\RYM\AppData\Local\Temp\tmpk9es11iy\model\data\model\assets]
[2025-02-23 14:10:34,084:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-23 14:10:34,097:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-23 14:10:34,098:INFO:common:created directory at: artifacts]
[2025-02-23 14:10:41,510:INFO:common:json file saved at:scores.json]
[2025-02-23 14:10:44,478:WARNING:save:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-02-23 14:10:44,954:INFO:builder_impl:Assets written to: C:\Users\RYM\AppData\Local\Temp\tmpvzxow_9e\model\data\model\assets]
[2025-02-23 18:32:24,188:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-23 18:32:24,207:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-23 18:32:24,209:INFO:common:created directory at: artifacts]
[2025-02-23 18:32:30,634:INFO:common:json file saved at:scores.json]
[2025-02-23 18:32:32,851:INFO:builder_impl:Assets written to: C:\Users\RYM\AppData\Local\Temp\tmp9bgvj_b9\model\data\model\assets]
[2025-02-23 18:38:23,245:INFO:_client:HTTP Request: GET https://dagshub.com/api/v1/repos/RymTangour/Kideny_Disease_Classification "HTTP/1.1 200 OK"]
[2025-02-23 18:38:23,250:INFO:helpers:Initialized MLflow to track repo "RymTangour/Kideny_Disease_Classification"]
[2025-02-23 18:38:23,252:INFO:helpers:Repository RymTangour/Kideny_Disease_Classification initialized!]
[2025-02-23 18:42:59,406:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-23 18:42:59,411:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-23 18:42:59,412:INFO:common:created directory at: artifacts]
[2025-02-23 18:43:06,813:INFO:common:json file saved at:scores.json]
[2025-02-23 18:43:09,102:INFO:builder_impl:Assets written to: C:\Users\RYM\AppData\Local\Temp\tmpwddmjo0q\model\data\model\assets]
[2025-02-23 18:50:30,456:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-23 18:50:30,467:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-23 18:50:30,471:INFO:common:created directory at: artifacts]
[2025-02-23 18:50:40,831:INFO:common:json file saved at:scores.json]
[2025-02-23 18:50:43,377:INFO:builder_impl:Assets written to: C:\Users\RYM\AppData\Local\Temp\tmp83wzmx7x\model\data\model\assets]
[2025-02-23 18:51:52,744:WARNING:connectionpool:Retrying (Retry(total=6, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /RymTangour/Kideny_Disease_Classification.mlflow/api/2.0/mlflow-artifacts/artifacts/a86bfbcd9098411f95a8c8439f64c854/09a00ebbf1dd490d9564da34f4fc72a2/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2025-02-23 18:52:27,933:WARNING:connectionpool:Retrying (Retry(total=5, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /RymTangour/Kideny_Disease_Classification.mlflow/api/2.0/mlflow-artifacts/artifacts/a86bfbcd9098411f95a8c8439f64c854/09a00ebbf1dd490d9564da34f4fc72a2/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2025-02-23 18:53:13,927:WARNING:connectionpool:Retrying (Retry(total=4, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /RymTangour/Kideny_Disease_Classification.mlflow/api/2.0/mlflow-artifacts/artifacts/a86bfbcd9098411f95a8c8439f64c854/09a00ebbf1dd490d9564da34f4fc72a2/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2025-02-23 18:54:30,355:WARNING:connectionpool:Retrying (Retry(total=3, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /RymTangour/Kideny_Disease_Classification.mlflow/api/2.0/mlflow-artifacts/artifacts/a86bfbcd9098411f95a8c8439f64c854/09a00ebbf1dd490d9564da34f4fc72a2/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2025-02-23 18:55:50,270:WARNING:connectionpool:Retrying (Retry(total=2, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /RymTangour/Kideny_Disease_Classification.mlflow/api/2.0/mlflow-artifacts/artifacts/a86bfbcd9098411f95a8c8439f64c854/09a00ebbf1dd490d9564da34f4fc72a2/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2025-02-23 18:57:27,435:WARNING:connectionpool:Retrying (Retry(total=1, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /RymTangour/Kideny_Disease_Classification.mlflow/api/2.0/mlflow-artifacts/artifacts/a86bfbcd9098411f95a8c8439f64c854/09a00ebbf1dd490d9564da34f4fc72a2/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2025-02-23 19:28:32,670:INFO:main: stage Data Ingestion stage  started]
[2025-02-23 19:28:32,672:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-23 19:28:32,686:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-23 19:28:32,687:INFO:common:created directory at: artifacts]
[2025-02-23 19:28:32,687:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-23 19:28:32,688:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-23 19:35:45,799:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-23 19:35:46,182:INFO:main:Stage Data Ingestion stage completed]
[2025-02-23 19:35:46,182:INFO:main: stage Prepare base model  started]
[2025-02-23 19:35:46,184:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-23 19:35:46,186:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-23 19:35:46,187:INFO:common:created directory at: artifacts]
[2025-02-23 19:35:46,187:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-23 19:35:46,580:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-23 19:35:46,743:INFO:main:Stage Prepare base model completed]
[2025-02-23 19:35:46,743:INFO:main: stage Training  started]
[2025-02-23 19:35:46,745:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-23 19:35:46,747:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-23 19:35:46,748:INFO:common:created directory at: artifacts]
[2025-02-23 19:35:46,748:INFO:common:created directory at: artifacts\training]
[2025-02-23 19:36:14,164:INFO:main:Stage Training completed]
[2025-02-23 19:36:14,164:INFO:main: stage Evaluation stage  started]
[2025-02-23 19:36:14,166:INFO:common:yaml file :config\config.yaml loaded succfully]
[2025-02-23 19:36:14,169:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-23 19:36:14,169:INFO:common:created directory at: artifacts]
[2025-02-23 19:36:20,158:INFO:common:json file saved at:scores.json]
[2025-02-23 19:36:21,772:INFO:builder_impl:Assets written to: C:\Users\RYM\AppData\Local\Temp\tmpipujjt0d\model\data\model\assets]
[2025-02-26 22:07:43,278:INFO:main: stage Data Ingestion stage  started]
[2025-02-26 22:07:43,282:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 22:07:43,308:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 22:07:43,311:INFO:common:created directory at: artifacts]
[2025-02-26 22:07:43,313:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-26 22:07:43,316:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 22:09:28,690:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 22:09:37,466:INFO:main:Stage Data Ingestion stage completed]
[2025-02-26 22:09:37,467:INFO:main: stage Prepare base model  started]
[2025-02-26 22:09:37,470:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 22:09:37,472:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 22:09:37,477:INFO:common:created directory at: artifacts]
[2025-02-26 22:09:37,487:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-26 22:10:57,450:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-26 22:10:57,810:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-26 22:10:58,213:INFO:main:Stage Prepare base model completed]
[2025-02-26 22:10:58,213:INFO:main: stage Training  started]
[2025-02-26 22:10:58,215:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 22:10:58,218:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 22:10:58,219:INFO:common:created directory at: artifacts]
[2025-02-26 22:10:58,221:INFO:common:created directory at: artifacts/training]
[2025-02-26 22:10:58,643:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-26 22:25:42,883:INFO:main: stage Data Ingestion stage  started]
[2025-02-26 22:25:42,886:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 22:25:42,888:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 22:25:42,891:INFO:common:created directory at: artifacts]
[2025-02-26 22:25:42,893:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-26 22:25:42,893:ERROR:main:DataIngestionConfig.__init__() got an unexpected keyword argument 'source_URL']
Traceback (most recent call last):
  File "/mnt/c/projet/Kideny_Disease_Classification/main.py", line 12, in <module>
    obj.main()
  File "/mnt/c/projet/Kideny_Disease_Classification/src/cnnClassifier/pipeline/stage_01_data_Ingestion.py", line 12, in main
    data_ingestion_config=config.get_data_ingestion_config()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/src/cnnClassifier/config/configuration.py", line 28, in get_data_ingestion_config
    data_ingestion_config = DataIngestionConfig(
                            ^^^^^^^^^^^^^^^^^^^^
TypeError: DataIngestionConfig.__init__() got an unexpected keyword argument 'source_URL'
[2025-02-26 22:29:03,659:INFO:main: stage Data Ingestion stage  started]
[2025-02-26 22:29:03,662:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 22:29:03,664:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 22:29:03,665:INFO:common:created directory at: artifacts]
[2025-02-26 22:29:03,668:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-26 22:29:03,668:ERROR:main:DataIngestionConfig.__init__() got an unexpected keyword argument 'source_URL']
Traceback (most recent call last):
  File "/mnt/c/projet/Kideny_Disease_Classification/main.py", line 12, in <module>
    obj.main()
  File "/mnt/c/projet/Kideny_Disease_Classification/src/cnnClassifier/pipeline/stage_01_data_Ingestion.py", line 12, in main
    data_ingestion_config=config.get_data_ingestion_config()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/src/cnnClassifier/config/configuration.py", line 28, in get_data_ingestion_config
    data_ingestion_config = DataIngestionConfig(
                            ^^^^^^^^^^^^^^^^^^^^
TypeError: DataIngestionConfig.__init__() got an unexpected keyword argument 'source_URL'
[2025-02-26 22:31:40,389:INFO:main: stage Data Ingestion stage  started]
[2025-02-26 22:31:40,392:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 22:31:40,394:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 22:31:40,395:INFO:common:created directory at: artifacts]
[2025-02-26 22:31:40,397:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-26 22:31:40,397:ERROR:main:DataIngestionConfig.__init__() got an unexpected keyword argument 'source_URL']
Traceback (most recent call last):
  File "/mnt/c/projet/Kideny_Disease_Classification/main.py", line 12, in <module>
    obj.main()
  File "/mnt/c/projet/Kideny_Disease_Classification/src/cnnClassifier/pipeline/stage_01_data_Ingestion.py", line 14, in main
    data_ingestion_config = config.get_data_ingestion_config()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/src/cnnClassifier/config/configuration.py", line 28, in get_data_ingestion_config
    data_ingestion_config = DataIngestionConfig(
                            ^^^^^^^^^^^^^^^^^^^^
TypeError: DataIngestionConfig.__init__() got an unexpected keyword argument 'source_URL'
[2025-02-26 22:37:34,131:INFO:main: stage Data Ingestion stage  started]
[2025-02-26 22:37:34,144:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 22:37:34,155:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 22:37:34,160:INFO:common:created directory at: artifacts]
[2025-02-26 22:37:34,171:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-26 22:37:34,173:ERROR:main:DataIngestionConfig.__init__() got an unexpected keyword argument 'source_URL']
Traceback (most recent call last):
  File "/mnt/c/projet/Kideny_Disease_Classification/main.py", line 12, in <module>
    obj.main()
  File "/mnt/c/projet/Kideny_Disease_Classification/src/cnnClassifier/pipeline/stage_01_data_Ingestion.py", line 14, in main
    data_ingestion_config = config.get_data_ingestion_config()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/src/cnnClassifier/config/configuration.py", line 28, in get_data_ingestion_config
    data_ingestion_config = DataIngestionConfig(
                            ^^^^^^^^^^^^^^^^^^^^
TypeError: DataIngestionConfig.__init__() got an unexpected keyword argument 'source_URL'
[2025-02-26 22:41:41,214:INFO:main: stage Data Ingestion stage  started]
[2025-02-26 22:41:41,226:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 22:41:41,237:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 22:41:41,242:INFO:common:created directory at: artifacts]
[2025-02-26 22:41:41,254:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-26 22:41:41,265:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 22:42:51,870:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 22:43:08,175:INFO:main:Stage Data Ingestion stage completed]
[2025-02-26 22:43:08,177:INFO:main: stage Prepare base model  started]
[2025-02-26 22:43:08,196:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 22:43:08,218:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 22:43:08,227:INFO:common:created directory at: artifacts]
[2025-02-26 22:43:08,245:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-26 22:43:16,667:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-26 22:43:17,280:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-26 22:43:18,032:INFO:main:Stage Prepare base model completed]
[2025-02-26 22:43:18,033:INFO:main: stage Training  started]
[2025-02-26 22:43:18,035:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 22:43:18,039:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 22:43:18,041:INFO:common:created directory at: artifacts]
[2025-02-26 22:43:18,045:INFO:common:created directory at: artifacts/training]
[2025-02-26 22:43:18,619:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-26 22:50:03,738:INFO:main: stage Data Ingestion stage  started]
[2025-02-26 22:50:03,741:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 22:50:03,744:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 22:50:03,745:INFO:common:created directory at: artifacts]
[2025-02-26 22:50:03,749:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-26 22:50:03,753:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 22:50:35,044:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 22:50:46,388:INFO:main:Stage Data Ingestion stage completed]
[2025-02-26 22:50:46,389:INFO:main: stage Prepare base model  started]
[2025-02-26 22:50:46,398:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 22:50:46,404:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 22:50:46,410:INFO:common:created directory at: artifacts]
[2025-02-26 22:50:46,416:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-26 22:50:52,770:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-26 22:50:53,177:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-26 22:50:53,847:INFO:main:Stage Prepare base model completed]
[2025-02-26 22:50:53,847:INFO:main: stage Training  started]
[2025-02-26 22:50:53,850:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 22:50:53,853:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 22:50:53,854:INFO:common:created directory at: artifacts]
[2025-02-26 22:50:53,856:INFO:common:created directory at: artifacts/training]
[2025-02-26 22:50:54,402:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-26 23:15:23,741:INFO:main: stage Data Ingestion stage  started]
[2025-02-26 23:15:23,760:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 23:15:23,779:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 23:15:23,784:INFO:common:created directory at: artifacts]
[2025-02-26 23:15:23,794:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-26 23:15:23,798:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 23:15:53,432:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 23:16:00,690:INFO:main:Stage Data Ingestion stage completed]
[2025-02-26 23:16:00,691:INFO:main: stage Prepare base model  started]
[2025-02-26 23:16:00,704:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 23:16:00,711:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 23:16:00,713:INFO:common:created directory at: artifacts]
[2025-02-26 23:16:00,717:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-26 23:16:04,799:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-26 23:16:05,353:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-26 23:16:05,935:INFO:main:Stage Prepare base model completed]
[2025-02-26 23:16:05,935:INFO:main: stage Training  started]
[2025-02-26 23:16:05,938:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 23:16:05,940:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 23:16:05,949:INFO:common:created directory at: artifacts]
[2025-02-26 23:16:05,967:INFO:common:created directory at: artifacts/training]
[2025-02-26 23:16:06,590:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-26 23:22:04,952:INFO:main: stage Data Ingestion stage  started]
[2025-02-26 23:22:04,954:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 23:22:04,956:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 23:22:04,958:INFO:common:created directory at: artifacts]
[2025-02-26 23:22:04,966:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-26 23:22:04,968:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 23:22:35,010:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 23:22:40,705:INFO:main:Stage Data Ingestion stage completed]
[2025-02-26 23:22:40,706:INFO:main: stage Prepare base model  started]
[2025-02-26 23:22:40,708:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 23:22:40,712:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 23:22:40,715:INFO:common:created directory at: artifacts]
[2025-02-26 23:22:40,718:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-26 23:22:44,348:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-26 23:22:47,354:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-26 23:22:47,836:INFO:main:Stage Prepare base model completed]
[2025-02-26 23:22:47,836:INFO:main: stage Training  started]
[2025-02-26 23:22:47,839:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 23:22:47,842:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 23:22:47,844:INFO:common:created directory at: artifacts]
[2025-02-26 23:22:47,847:INFO:common:created directory at: artifacts/training]
[2025-02-26 23:25:10,740:INFO:main: stage Data Ingestion stage  started]
[2025-02-26 23:25:10,743:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 23:25:10,745:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 23:25:10,746:INFO:common:created directory at: artifacts]
[2025-02-26 23:25:10,749:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-26 23:25:10,751:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 23:25:37,006:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 23:25:46,247:INFO:main:Stage Data Ingestion stage completed]
[2025-02-26 23:25:46,248:INFO:main: stage Prepare base model  started]
[2025-02-26 23:25:46,265:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 23:25:46,269:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 23:25:46,270:INFO:common:created directory at: artifacts]
[2025-02-26 23:25:46,273:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-26 23:25:50,303:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-26 23:25:50,708:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-26 23:25:51,079:INFO:main:Stage Prepare base model completed]
[2025-02-26 23:25:51,079:INFO:main: stage Training  started]
[2025-02-26 23:25:51,082:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 23:25:51,091:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 23:25:51,094:INFO:common:created directory at: artifacts]
[2025-02-26 23:25:51,098:INFO:common:created directory at: artifacts/training]
[2025-02-26 23:25:51,766:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-26 23:26:23,402:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-26 23:26:24,045:INFO:main:Stage Training completed]
[2025-02-26 23:26:24,045:INFO:main: stage Evaluation stage  started]
[2025-02-26 23:26:24,048:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 23:26:24,050:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 23:26:24,058:INFO:common:created directory at: artifacts]
[2025-02-26 23:26:24,901:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-26 23:26:27,506:INFO:common:json file saved at:scores.json]
[2025-02-26 23:42:53,786:INFO:main: stage Data Ingestion stage  started]
[2025-02-26 23:42:53,789:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 23:42:53,792:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 23:42:53,794:INFO:common:created directory at: artifacts]
[2025-02-26 23:42:53,796:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-26 23:42:53,800:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 23:43:28,827:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 23:43:45,448:INFO:main:Stage Data Ingestion stage completed]
[2025-02-26 23:43:45,450:INFO:main: stage Prepare base model  started]
[2025-02-26 23:43:45,462:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 23:43:45,475:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 23:43:45,483:INFO:common:created directory at: artifacts]
[2025-02-26 23:43:45,496:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-26 23:43:58,712:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-26 23:43:59,519:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-26 23:44:00,301:INFO:main:Stage Prepare base model completed]
[2025-02-26 23:44:00,302:INFO:main: stage Training  started]
[2025-02-26 23:44:00,310:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 23:44:00,317:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 23:44:00,322:INFO:common:created directory at: artifacts]
[2025-02-26 23:44:00,330:INFO:common:created directory at: artifacts/training]
[2025-02-26 23:44:01,358:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-26 23:45:02,648:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-26 23:45:03,770:INFO:main:Stage Training completed]
[2025-02-26 23:45:03,771:INFO:main: stage Evaluation stage  started]
[2025-02-26 23:45:03,776:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 23:45:03,784:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 23:45:03,790:INFO:common:created directory at: artifacts]
[2025-02-26 23:45:05,365:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-26 23:45:09,838:INFO:common:json file saved at:scores.json]
[2025-02-26 23:54:25,750:INFO:main: stage Data Ingestion stage  started]
[2025-02-26 23:54:25,758:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 23:54:25,765:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 23:54:25,770:INFO:common:created directory at: artifacts]
[2025-02-26 23:54:25,778:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-26 23:54:25,788:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 23:55:04,254:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 23:55:19,504:INFO:main:Stage Data Ingestion stage completed]
[2025-02-26 23:55:19,506:INFO:main: stage Prepare base model  started]
[2025-02-26 23:55:19,518:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 23:55:19,531:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 23:55:19,540:INFO:common:created directory at: artifacts]
[2025-02-26 23:55:19,552:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-26 23:55:22,533:INFO:main:Stage Prepare base model completed]
[2025-02-26 23:55:22,534:INFO:main: stage Training  started]
[2025-02-26 23:55:22,537:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 23:55:22,542:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 23:55:22,546:INFO:common:created directory at: artifacts]
[2025-02-26 23:55:22,551:INFO:common:created directory at: artifacts/training]
[2025-02-26 23:56:21,670:INFO:main:Stage Training completed]
[2025-02-26 23:56:21,670:INFO:main: stage Evaluation stage  started]
[2025-02-26 23:56:21,675:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-26 23:56:21,680:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-26 23:56:21,683:INFO:common:created directory at: artifacts]
[2025-02-26 23:56:29,656:INFO:common:json file saved at:scores.json]
[2025-02-27 00:01:52,675:WARNING:font_manager:Matplotlib is building the font cache; this may take a moment.]
[2025-02-27 00:01:53,532:INFO:font_manager:generated new fontManager]
[2025-02-27 00:02:46,783:INFO:main: stage Data Ingestion stage  started]
[2025-02-27 00:02:46,785:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:02:46,787:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:02:46,788:INFO:common:created directory at: artifacts]
[2025-02-27 00:02:46,790:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-27 00:02:46,792:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-27 00:03:23,619:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-27 00:03:30,097:INFO:main:Stage Data Ingestion stage completed]
[2025-02-27 00:03:30,099:INFO:main: stage Prepare base model  started]
[2025-02-27 00:03:30,112:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:03:30,116:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:03:30,118:INFO:common:created directory at: artifacts]
[2025-02-27 00:03:30,120:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-27 00:04:02,116:INFO:main:Stage Prepare base model completed]
[2025-02-27 00:04:02,116:INFO:main: stage Training  started]
[2025-02-27 00:04:02,119:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:04:02,122:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:04:02,123:INFO:common:created directory at: artifacts]
[2025-02-27 00:04:02,126:INFO:common:created directory at: artifacts/training]
[2025-02-27 00:04:44,778:INFO:main:Stage Training completed]
[2025-02-27 00:04:44,780:INFO:main: stage Evaluation stage  started]
[2025-02-27 00:04:44,810:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:04:44,846:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:04:44,862:INFO:common:created directory at: artifacts]
[2025-02-27 00:04:50,096:INFO:common:json file saved at:scores.json]
[2025-02-27 00:06:58,541:INFO:main: stage Data Ingestion stage  started]
[2025-02-27 00:06:58,543:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:06:58,546:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:06:58,547:INFO:common:created directory at: artifacts]
[2025-02-27 00:06:58,549:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-27 00:06:58,553:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-27 00:07:31,762:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-27 00:07:44,097:INFO:main:Stage Data Ingestion stage completed]
[2025-02-27 00:07:44,098:INFO:main: stage Prepare base model  started]
[2025-02-27 00:07:44,117:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:07:44,133:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:07:44,141:INFO:common:created directory at: artifacts]
[2025-02-27 00:07:44,155:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-27 00:07:50,556:INFO:main:Stage Prepare base model completed]
[2025-02-27 00:07:50,557:INFO:main: stage Training  started]
[2025-02-27 00:07:50,571:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:07:50,585:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:07:50,605:INFO:common:created directory at: artifacts]
[2025-02-27 00:07:50,624:INFO:common:created directory at: artifacts/training]
[2025-02-27 00:08:47,887:INFO:main:Stage Training completed]
[2025-02-27 00:08:47,887:INFO:main: stage Evaluation stage  started]
[2025-02-27 00:08:47,891:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:08:47,896:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:08:47,899:INFO:common:created directory at: artifacts]
[2025-02-27 00:08:53,468:INFO:common:json file saved at:scores.json]
[2025-02-27 00:19:40,790:INFO:main: stage Data Ingestion stage  started]
[2025-02-27 00:19:40,793:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:19:40,795:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:19:40,797:INFO:common:created directory at: artifacts]
[2025-02-27 00:19:40,799:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-27 00:19:40,801:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-27 00:20:12,913:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-27 00:20:29,693:INFO:main:Stage Data Ingestion stage completed]
[2025-02-27 00:20:29,695:INFO:main: stage Prepare base model  started]
[2025-02-27 00:20:29,723:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:20:29,746:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:20:29,760:INFO:common:created directory at: artifacts]
[2025-02-27 00:20:29,776:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-27 00:20:33,690:INFO:main:Stage Prepare base model completed]
[2025-02-27 00:20:33,691:INFO:main: stage Training  started]
[2025-02-27 00:20:33,696:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:20:33,711:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:20:33,717:INFO:common:created directory at: artifacts]
[2025-02-27 00:20:33,729:INFO:common:created directory at: artifacts/training]
[2025-02-27 00:21:25,727:INFO:main:Stage Training completed]
[2025-02-27 00:21:25,727:INFO:main: stage Evaluation stage  started]
[2025-02-27 00:21:25,730:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:21:25,733:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:21:25,738:INFO:common:created directory at: artifacts]
[2025-02-27 00:21:33,630:INFO:common:json file saved at:scores.json]
[2025-02-27 00:29:13,173:INFO:main: stage Data Ingestion stage  started]
[2025-02-27 00:29:13,176:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:29:13,178:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:29:13,179:INFO:common:created directory at: artifacts]
[2025-02-27 00:29:13,181:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-27 00:29:13,183:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-27 00:29:40,707:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-27 00:29:46,860:INFO:main:Stage Data Ingestion stage completed]
[2025-02-27 00:29:46,861:INFO:main: stage Prepare base model  started]
[2025-02-27 00:29:46,867:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:29:46,871:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:29:46,874:INFO:common:created directory at: artifacts]
[2025-02-27 00:29:46,878:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-27 00:29:48,646:INFO:main:Stage Prepare base model completed]
[2025-02-27 00:29:48,646:INFO:main: stage Training  started]
[2025-02-27 00:29:48,648:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:29:48,651:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:29:48,652:INFO:common:created directory at: artifacts]
[2025-02-27 00:29:48,654:INFO:common:created directory at: artifacts/training]
[2025-02-27 00:30:20,379:INFO:main:Stage Training completed]
[2025-02-27 00:30:20,379:INFO:main: stage Evaluation stage  started]
[2025-02-27 00:30:20,390:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:30:20,396:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:30:20,399:INFO:common:created directory at: artifacts]
[2025-02-27 00:30:23,576:INFO:common:json file saved at:scores.json]
[2025-02-27 00:42:58,652:INFO:main: stage Data Ingestion stage  started]
[2025-02-27 00:42:58,662:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:42:58,669:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:42:58,674:INFO:common:created directory at: artifacts]
[2025-02-27 00:42:58,683:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-27 00:42:58,691:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-27 00:43:31,721:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-27 00:43:46,236:INFO:main:Stage Data Ingestion stage completed]
[2025-02-27 00:43:46,238:INFO:main: stage Prepare base model  started]
[2025-02-27 00:43:46,250:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:43:46,265:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:43:46,275:INFO:common:created directory at: artifacts]
[2025-02-27 00:43:46,291:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-27 00:44:01,328:INFO:main:Stage Prepare base model completed]
[2025-02-27 00:44:01,331:INFO:main: stage Training  started]
[2025-02-27 00:44:01,362:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:44:01,397:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:44:01,414:INFO:common:created directory at: artifacts]
[2025-02-27 00:44:01,431:INFO:common:created directory at: artifacts/training]
[2025-02-27 00:44:41,170:INFO:main:Stage Training completed]
[2025-02-27 00:44:41,170:INFO:main: stage Evaluation stage  started]
[2025-02-27 00:44:41,174:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:44:41,178:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:44:41,202:INFO:common:created directory at: artifacts]
[2025-02-27 00:44:44,226:INFO:common:json file saved at:scores.json]
[2025-02-27 00:50:55,636:INFO:main: stage Data Ingestion stage  started]
[2025-02-27 00:50:55,638:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:50:55,641:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:50:55,642:INFO:common:created directory at: artifacts]
[2025-02-27 00:50:55,644:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-27 00:50:55,646:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-27 00:51:26,972:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-27 00:51:34,650:INFO:main:Stage Data Ingestion stage completed]
[2025-02-27 00:51:34,650:INFO:main: stage Prepare base model  started]
[2025-02-27 00:51:34,655:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:51:34,659:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:51:34,661:INFO:common:created directory at: artifacts]
[2025-02-27 00:51:34,663:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-27 00:51:36,673:INFO:main:Stage Prepare base model completed]
[2025-02-27 00:51:36,673:INFO:main: stage Training  started]
[2025-02-27 00:51:36,689:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:51:36,696:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:51:36,699:INFO:common:created directory at: artifacts]
[2025-02-27 00:51:36,705:INFO:common:created directory at: artifacts/training]
[2025-02-27 00:52:09,654:INFO:main:Stage Training completed]
[2025-02-27 00:52:09,655:INFO:main: stage Evaluation stage  started]
[2025-02-27 00:52:09,657:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:52:09,659:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:52:09,661:INFO:common:created directory at: artifacts]
[2025-02-27 00:52:12,818:INFO:common:json file saved at:scores.json]
[2025-02-27 00:58:12,741:INFO:main: stage Data Ingestion stage  started]
[2025-02-27 00:58:12,757:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:58:12,770:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:58:12,776:INFO:common:created directory at: artifacts]
[2025-02-27 00:58:12,790:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-27 00:58:12,801:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-27 00:58:40,791:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-27 00:58:53,555:INFO:main:Stage Data Ingestion stage completed]
[2025-02-27 00:58:53,556:INFO:main: stage Prepare base model  started]
[2025-02-27 00:58:53,571:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:58:53,584:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:58:53,594:INFO:common:created directory at: artifacts]
[2025-02-27 00:58:53,609:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-27 00:58:56,698:INFO:main:Stage Prepare base model completed]
[2025-02-27 00:58:56,699:INFO:main: stage Training  started]
[2025-02-27 00:58:56,703:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:58:56,709:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:58:56,713:INFO:common:created directory at: artifacts]
[2025-02-27 00:58:56,723:INFO:common:created directory at: artifacts/training]
[2025-02-27 00:59:46,650:INFO:main:Stage Training completed]
[2025-02-27 00:59:46,651:INFO:main: stage Evaluation stage  started]
[2025-02-27 00:59:46,661:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 00:59:46,687:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 00:59:46,698:INFO:common:created directory at: artifacts]
[2025-02-27 00:59:53,842:INFO:common:json file saved at:scores.json]
[2025-02-27 01:06:44,895:INFO:main: stage Data Ingestion stage  started]
[2025-02-27 01:06:44,898:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 01:06:44,900:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 01:06:44,901:INFO:common:created directory at: artifacts]
[2025-02-27 01:06:44,902:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-27 01:06:44,906:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-27 01:07:19,334:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-27 01:07:26,319:INFO:main:Stage Data Ingestion stage completed]
[2025-02-27 01:07:26,319:INFO:main: stage Prepare base model  started]
[2025-02-27 01:07:26,326:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 01:07:26,372:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 01:07:26,383:INFO:common:created directory at: artifacts]
[2025-02-27 01:07:26,409:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-27 01:07:28,785:INFO:main:Stage Prepare base model completed]
[2025-02-27 01:07:28,786:INFO:main: stage Training  started]
[2025-02-27 01:07:28,792:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 01:07:28,798:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 01:07:28,801:INFO:common:created directory at: artifacts]
[2025-02-27 01:07:28,810:INFO:common:created directory at: artifacts/training]
[2025-02-27 01:08:01,724:INFO:main:Stage Training completed]
[2025-02-27 01:08:01,725:INFO:main: stage Evaluation stage  started]
[2025-02-27 01:08:01,727:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-27 01:08:01,730:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-27 01:08:01,732:INFO:common:created directory at: artifacts]
[2025-02-27 01:08:05,602:INFO:common:json file saved at:scores.json]
[2025-02-28 15:49:32,702:INFO:main: stage Data Ingestion stage  started]
[2025-02-28 15:49:32,715:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-28 15:49:32,724:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-28 15:49:32,729:INFO:common:created directory at: artifacts]
[2025-02-28 15:49:32,737:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-28 15:49:32,746:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 15:49:48,652:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 15:49:56,790:INFO:main:Stage Data Ingestion stage completed]
[2025-02-28 15:49:56,792:INFO:main: stage Prepare base model  started]
[2025-02-28 15:49:56,800:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-28 15:49:56,805:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-28 15:49:56,808:INFO:common:created directory at: artifacts]
[2025-02-28 15:49:56,812:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-28 15:50:14,582:INFO:main:Stage Prepare base model completed]
[2025-02-28 15:50:14,582:INFO:main: stage Training  started]
[2025-02-28 15:50:14,604:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-28 15:50:14,617:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-28 15:50:14,621:INFO:common:created directory at: artifacts]
[2025-02-28 15:50:14,626:INFO:common:created directory at: artifacts/training]
[2025-02-28 15:51:54,500:INFO:main:Stage Training completed]
[2025-02-28 15:51:54,501:INFO:main: stage Evaluation stage  started]
[2025-02-28 15:51:54,537:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-28 15:51:54,552:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-28 15:51:54,562:INFO:common:created directory at: artifacts]
[2025-02-28 15:52:03,114:INFO:common:json file saved at:scores.json]
[2025-02-28 16:21:10,399:INFO:main: stage Data Ingestion stage  started]
[2025-02-28 16:21:10,407:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-28 16:21:10,414:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-28 16:21:10,417:INFO:common:created directory at: artifacts]
[2025-02-28 16:21:10,422:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-28 16:21:10,428:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 16:21:24,633:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 16:21:29,770:INFO:main:Stage Data Ingestion stage completed]
[2025-02-28 16:21:29,771:INFO:main: stage Prepare base model  started]
[2025-02-28 16:21:29,776:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-28 16:21:29,781:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-28 16:21:29,783:INFO:common:created directory at: artifacts]
[2025-02-28 16:21:29,790:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-28 16:21:44,319:INFO:main:Stage Prepare base model completed]
[2025-02-28 16:21:44,320:INFO:main: stage Training  started]
[2025-02-28 16:21:44,327:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-28 16:21:44,338:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-28 16:21:44,344:INFO:common:created directory at: artifacts]
[2025-02-28 16:21:44,362:INFO:common:created directory at: artifacts/training]
[2025-02-28 16:23:09,981:INFO:main:Stage Training completed]
[2025-02-28 16:23:09,982:INFO:main: stage Evaluation stage  started]
[2025-02-28 16:23:09,988:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-28 16:23:09,994:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-28 16:23:09,998:INFO:common:created directory at: artifacts]
[2025-02-28 16:23:12,696:INFO:common:json file saved at:scores.json]
[2025-02-28 16:28:14,231:INFO:_client:HTTP Request: POST https://dagshub.com/login/oauth/middleman "HTTP/1.1 504 Gateway Timeout"]
[2025-02-28 16:39:24,031:INFO:main: stage Data Ingestion stage  started]
[2025-02-28 16:39:24,050:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-28 16:39:24,064:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-28 16:39:24,070:INFO:common:created directory at: artifacts]
[2025-02-28 16:39:24,083:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-28 16:39:24,094:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 16:39:37,456:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 16:39:57,849:INFO:main:Stage Data Ingestion stage completed]
[2025-02-28 16:39:57,851:INFO:main: stage Prepare base model  started]
[2025-02-28 16:39:57,869:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-28 16:39:57,889:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-28 16:39:57,898:INFO:common:created directory at: artifacts]
[2025-02-28 16:39:57,916:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-28 16:40:40,632:INFO:main:Stage Prepare base model completed]
[2025-02-28 16:40:40,632:INFO:main: stage Training  started]
[2025-02-28 16:40:40,639:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-28 16:40:40,658:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-28 16:40:40,664:INFO:common:created directory at: artifacts]
[2025-02-28 16:40:40,677:INFO:common:created directory at: artifacts/training]
[2025-02-28 16:43:11,402:INFO:main:Stage Training completed]
[2025-02-28 16:43:11,404:INFO:main: stage Evaluation stage  started]
[2025-02-28 16:43:11,414:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-28 16:43:11,427:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-28 16:43:11,434:INFO:common:created directory at: artifacts]
[2025-02-28 16:43:19,169:INFO:common:json file saved at:scores.json]
[2025-02-28 16:45:10,464:INFO:_client:HTTP Request: POST https://dagshub.com/login/oauth/middleman "HTTP/1.1 200 OK"]
[2025-02-28 16:45:10,814:INFO:_client:HTTP Request: POST https://dagshub.com/login/oauth/access_token "HTTP/1.1 200 OK"]
[2025-02-28 16:45:11,227:INFO:_client:HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-02-28 16:45:11,247:INFO:helpers:Accessing as RymTangour]
[2025-02-28 16:45:11,744:INFO:_client:HTTP Request: GET https://dagshub.com/api/v1/repos/RymTangour/Kideny_Disease_Classification "HTTP/1.1 200 OK"]
[2025-02-28 16:45:12,179:INFO:_client:HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-02-28 16:45:12,181:INFO:helpers:Initialized MLflow to track repo "RymTangour/Kideny_Disease_Classification"]
[2025-02-28 16:45:12,184:INFO:helpers:Repository RymTangour/Kideny_Disease_Classification initialized!]
[2025-02-28 16:55:14,388:INFO:main: stage Data Ingestion stage  started]
[2025-02-28 16:55:14,397:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-28 16:55:14,402:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-28 16:55:14,404:INFO:common:created directory at: artifacts]
[2025-02-28 16:55:14,407:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-28 16:55:14,416:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 16:55:27,489:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 16:55:42,903:INFO:main:Stage Data Ingestion stage completed]
[2025-02-28 16:55:42,903:INFO:main: stage Prepare base model  started]
[2025-02-28 16:55:42,910:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-28 16:55:42,916:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-28 16:55:42,920:INFO:common:created directory at: artifacts]
[2025-02-28 16:55:42,925:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-28 16:56:25,216:INFO:main:Stage Prepare base model completed]
[2025-02-28 16:56:25,216:INFO:main: stage Training  started]
[2025-02-28 16:56:25,235:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-28 16:56:25,250:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-28 16:56:25,252:INFO:common:created directory at: artifacts]
[2025-02-28 16:56:25,256:INFO:common:created directory at: artifacts/training]
[2025-02-28 16:58:11,756:INFO:main:Stage Training completed]
[2025-02-28 16:58:11,764:INFO:main: stage Evaluation stage  started]
[2025-02-28 16:58:11,789:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-28 16:58:11,819:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-28 16:58:11,832:INFO:common:created directory at: artifacts]
[2025-02-28 17:07:10,018:INFO:main: stage Data Ingestion stage  started]
[2025-02-28 17:07:10,028:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-28 17:07:10,035:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-28 17:07:10,038:INFO:common:created directory at: artifacts]
[2025-02-28 17:07:10,042:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-28 17:07:10,047:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 17:07:25,485:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 17:07:35,265:INFO:main:Stage Data Ingestion stage completed]
[2025-02-28 17:07:35,265:INFO:main: stage Prepare base model  started]
[2025-02-28 17:07:35,270:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-28 17:07:35,274:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-28 17:07:35,276:INFO:common:created directory at: artifacts]
[2025-02-28 17:07:35,280:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-28 17:07:49,285:INFO:main:Stage Prepare base model completed]
[2025-02-28 17:07:49,286:INFO:main: stage Training  started]
[2025-02-28 17:07:49,296:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-28 17:07:49,314:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-28 17:07:49,321:INFO:common:created directory at: artifacts]
[2025-02-28 17:07:49,329:INFO:common:created directory at: artifacts/training]
[2025-02-28 17:09:40,517:INFO:main:Stage Training completed]
[2025-02-28 17:09:40,520:INFO:main: stage Evaluation stage  started]
[2025-02-28 17:09:40,542:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-28 17:09:40,558:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-28 17:09:40,563:INFO:common:created directory at: artifacts]
[2025-02-28 17:09:48,373:INFO:common:json file saved at:scores.json]
[2025-02-28 17:09:48,691:INFO:_client:HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-02-28 17:09:48,696:INFO:helpers:Accessing as RymTangour]
[2025-02-28 17:09:49,173:INFO:_client:HTTP Request: GET https://dagshub.com/api/v1/repos/RymTangour/Kideny_Disease_Classification "HTTP/1.1 200 OK"]
[2025-02-28 17:09:49,490:INFO:_client:HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-02-28 17:09:49,493:INFO:helpers:Initialized MLflow to track repo "RymTangour/Kideny_Disease_Classification"]
[2025-02-28 17:09:49,494:INFO:helpers:Repository RymTangour/Kideny_Disease_Classification initialized!]
[2025-02-28 17:48:43,506:INFO:main: stage Data Ingestion stage  started]
[2025-02-28 17:48:43,512:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-28 17:48:43,516:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-28 17:48:43,520:INFO:common:created directory at: artifacts]
[2025-02-28 17:48:43,523:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-28 17:48:43,526:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 17:48:57,965:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 17:49:03,306:INFO:main:Stage Data Ingestion stage completed]
[2025-02-28 17:49:03,307:INFO:main: stage Prepare base model  started]
[2025-02-28 17:49:03,310:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-28 17:49:03,315:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-28 17:49:03,319:INFO:common:created directory at: artifacts]
[2025-02-28 17:49:03,322:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-02-28 17:49:15,518:INFO:main:Stage Prepare base model completed]
[2025-02-28 17:49:15,519:INFO:main: stage Training  started]
[2025-02-28 17:49:15,530:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-28 17:49:15,547:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-28 17:49:15,551:INFO:common:created directory at: artifacts]
[2025-02-28 17:49:15,555:INFO:common:created directory at: artifacts/training]
[2025-02-28 17:50:46,722:INFO:main:Stage Training completed]
[2025-02-28 17:50:46,722:INFO:main: stage Evaluation stage  started]
[2025-02-28 17:50:46,728:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-02-28 17:50:46,734:INFO:common:yaml file :params.yaml loaded succfully]
[2025-02-28 17:50:46,738:INFO:common:created directory at: artifacts]
[2025-02-28 17:50:50,820:INFO:common:json file saved at:scores.json]
[2025-02-28 17:50:51,113:INFO:_client:HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-02-28 17:50:51,117:INFO:helpers:Accessing as RymTangour]
[2025-02-28 17:50:51,495:INFO:_client:HTTP Request: GET https://dagshub.com/api/v1/repos/RymTangour/Kideny_Disease_Classification "HTTP/1.1 200 OK"]
[2025-02-28 17:50:51,808:INFO:_client:HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-02-28 17:50:51,811:INFO:helpers:Initialized MLflow to track repo "RymTangour/Kideny_Disease_Classification"]
[2025-02-28 17:50:51,812:INFO:helpers:Repository RymTangour/Kideny_Disease_Classification initialized!]
[2025-03-01 13:44:56,969:INFO:main: stage Data Ingestion stage  started]
[2025-03-01 13:44:56,981:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-01 13:44:57,004:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-01 13:44:57,006:INFO:common:created directory at: artifacts]
[2025-03-01 13:44:57,010:INFO:common:created directory at: artifacts/data_ingestion]
[2025-03-01 13:44:57,049:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-01 13:48:19,869:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-01 13:48:27,924:INFO:main:Stage Data Ingestion stage completed]
[2025-03-01 13:48:27,925:INFO:main: stage Prepare base model  started]
[2025-03-01 13:48:27,940:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-01 13:48:27,952:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-01 13:48:27,967:INFO:common:created directory at: artifacts]
[2025-03-01 13:48:27,977:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-03-01 13:48:38,247:INFO:main:Stage Prepare base model completed]
[2025-03-01 13:48:38,257:INFO:main: stage Training  started]
[2025-03-01 13:48:38,265:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-01 13:48:38,288:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-01 13:48:38,294:INFO:common:created directory at: artifacts]
[2025-03-01 13:48:38,301:INFO:common:created directory at: artifacts/training]
[2025-03-01 13:50:02,716:INFO:main:Stage Training completed]
[2025-03-01 13:50:02,716:INFO:main: stage Evaluation stage  started]
[2025-03-01 13:50:02,718:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-01 13:50:02,721:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-01 13:50:02,723:INFO:common:created directory at: artifacts]
[2025-03-01 13:50:05,685:INFO:common:json file saved at:scores.json]
[2025-03-01 13:50:06,209:INFO:_client:HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-03-01 13:50:06,214:INFO:helpers:Accessing as RymTangour]
[2025-03-01 13:50:06,724:INFO:_client:HTTP Request: GET https://dagshub.com/api/v1/repos/RymTangour/Kideny_Disease_Classification "HTTP/1.1 200 OK"]
[2025-03-01 13:50:07,123:INFO:_client:HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-03-01 13:50:07,125:INFO:helpers:Initialized MLflow to track repo "RymTangour/Kideny_Disease_Classification"]
[2025-03-01 13:50:07,126:INFO:helpers:Repository RymTangour/Kideny_Disease_Classification initialized!]
[2025-03-01 14:37:44,984:INFO:main: stage Data Ingestion stage  started]
[2025-03-01 14:37:45,009:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-01 14:37:45,029:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-01 14:37:45,032:INFO:common:created directory at: artifacts]
[2025-03-01 14:37:45,037:INFO:common:created directory at: artifacts/data_ingestion]
[2025-03-01 14:37:45,041:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-01 14:42:08,075:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-01 14:42:18,612:INFO:main:Stage Data Ingestion stage completed]
[2025-03-01 14:42:18,613:INFO:main: stage Prepare base model  started]
[2025-03-01 14:42:18,617:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-01 14:42:18,621:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-01 14:42:18,623:INFO:common:created directory at: artifacts]
[2025-03-01 14:42:18,626:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-03-01 14:42:28,264:INFO:main:Stage Prepare base model completed]
[2025-03-01 14:42:28,265:INFO:main: stage Training  started]
[2025-03-01 14:42:28,271:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-01 14:42:28,277:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-01 14:42:28,280:INFO:common:created directory at: artifacts]
[2025-03-01 14:42:28,284:INFO:common:created directory at: artifacts/training]
[2025-03-01 14:43:47,488:INFO:main:Stage Training completed]
[2025-03-01 14:43:47,488:INFO:main: stage Evaluation stage  started]
[2025-03-01 14:43:47,494:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-01 14:43:47,500:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-01 14:43:47,503:INFO:common:created directory at: artifacts]
[2025-03-01 14:43:50,964:INFO:common:json file saved at:scores.json]
[2025-03-01 14:43:51,536:INFO:_client:HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-03-01 14:43:51,539:INFO:helpers:Accessing as RymTangour]
[2025-03-01 14:43:52,054:INFO:_client:HTTP Request: GET https://dagshub.com/api/v1/repos/RymTangour/Kideny_Disease_Classification "HTTP/1.1 200 OK"]
[2025-03-01 14:43:52,452:INFO:_client:HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-03-01 14:43:52,456:INFO:helpers:Initialized MLflow to track repo "RymTangour/Kideny_Disease_Classification"]
[2025-03-01 14:43:52,458:INFO:helpers:Repository RymTangour/Kideny_Disease_Classification initialized!]
[2025-03-01 15:10:07,684:WARNING:connectionpool:Retrying (Retry(total=6, connect=7, read=6, redirect=7, status=7)) after connection broken by 'TimeoutError('The write operation timed out')': /RymTangour/Kideny_Disease_Classification.mlflow/api/2.0/mlflow-artifacts/artifacts/a86bfbcd9098411f95a8c8439f64c854/34643c8284394131854467eac4133df0/artifacts/model/data/model.keras]
[2025-03-01 15:10:22,402:WARNING:connectionpool:Retrying (Retry(total=5, connect=6, read=6, redirect=7, status=7)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f89f79338c0>: Failed to resolve 'dagshub.com' ([Errno -3] Temporary failure in name resolution)")': /RymTangour/Kideny_Disease_Classification.mlflow/api/2.0/mlflow-artifacts/artifacts/a86bfbcd9098411f95a8c8439f64c854/34643c8284394131854467eac4133df0/artifacts/model/data/model.keras]
[2025-03-01 15:10:41,257:WARNING:connectionpool:Retrying (Retry(total=4, connect=5, read=6, redirect=7, status=7)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f892c58ecc0>: Failed to resolve 'dagshub.com' ([Errno -3] Temporary failure in name resolution)")': /RymTangour/Kideny_Disease_Classification.mlflow/api/2.0/mlflow-artifacts/artifacts/a86bfbcd9098411f95a8c8439f64c854/34643c8284394131854467eac4133df0/artifacts/model/data/model.keras]
[2025-03-01 15:11:07,904:WARNING:connectionpool:Retrying (Retry(total=3, connect=4, read=6, redirect=7, status=7)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f892c58eea0>: Failed to resolve 'dagshub.com' ([Errno -3] Temporary failure in name resolution)")': /RymTangour/Kideny_Disease_Classification.mlflow/api/2.0/mlflow-artifacts/artifacts/a86bfbcd9098411f95a8c8439f64c854/34643c8284394131854467eac4133df0/artifacts/model/data/model.keras]
[2025-03-01 15:11:50,032:WARNING:connectionpool:Retrying (Retry(total=2, connect=3, read=6, redirect=7, status=7)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f892c58f080>: Failed to resolve 'dagshub.com' ([Errno -3] Temporary failure in name resolution)")': /RymTangour/Kideny_Disease_Classification.mlflow/api/2.0/mlflow-artifacts/artifacts/a86bfbcd9098411f95a8c8439f64c854/34643c8284394131854467eac4133df0/artifacts/model/data/model.keras]
[2025-03-01 15:13:04,850:WARNING:connectionpool:Retrying (Retry(total=1, connect=2, read=6, redirect=7, status=7)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f892c58f260>: Failed to resolve 'dagshub.com' ([Errno -3] Temporary failure in name resolution)")': /RymTangour/Kideny_Disease_Classification.mlflow/api/2.0/mlflow-artifacts/artifacts/a86bfbcd9098411f95a8c8439f64c854/34643c8284394131854467eac4133df0/artifacts/model/data/model.keras]
[2025-03-01 15:15:14,865:WARNING:connectionpool:Retrying (Retry(total=0, connect=1, read=6, redirect=7, status=7)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f892c58f440>: Failed to resolve 'dagshub.com' ([Errno -3] Temporary failure in name resolution)")': /RymTangour/Kideny_Disease_Classification.mlflow/api/2.0/mlflow-artifacts/artifacts/a86bfbcd9098411f95a8c8439f64c854/34643c8284394131854467eac4133df0/artifacts/model/data/model.keras]
[2025-03-01 15:15:34,922:WARNING:connectionpool:Retrying (Retry(total=6, connect=6, read=7, redirect=7, status=7)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f892c5b0410>: Failed to resolve 'dagshub.com' ([Errno -3] Temporary failure in name resolution)")': /RymTangour/Kideny_Disease_Classification.mlflow/api/2.0/mlflow/runs/get?run_uuid=34643c8284394131854467eac4133df0&run_id=34643c8284394131854467eac4133df0]
[2025-03-01 15:15:49,412:WARNING:connectionpool:Retrying (Retry(total=5, connect=5, read=7, redirect=7, status=7)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f892c5b0680>: Failed to resolve 'dagshub.com' ([Errno -3] Temporary failure in name resolution)")': /RymTangour/Kideny_Disease_Classification.mlflow/api/2.0/mlflow/runs/get?run_uuid=34643c8284394131854467eac4133df0&run_id=34643c8284394131854467eac4133df0]
[2025-03-01 15:16:08,191:WARNING:connectionpool:Retrying (Retry(total=4, connect=4, read=7, redirect=7, status=7)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f892c5b0860>: Failed to resolve 'dagshub.com' ([Errno -3] Temporary failure in name resolution)")': /RymTangour/Kideny_Disease_Classification.mlflow/api/2.0/mlflow/runs/get?run_uuid=34643c8284394131854467eac4133df0&run_id=34643c8284394131854467eac4133df0]
[2025-03-01 15:16:34,501:WARNING:connectionpool:Retrying (Retry(total=3, connect=3, read=7, redirect=7, status=7)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f892c5b0a40>: Failed to resolve 'dagshub.com' ([Errno -3] Temporary failure in name resolution)")': /RymTangour/Kideny_Disease_Classification.mlflow/api/2.0/mlflow/runs/get?run_uuid=34643c8284394131854467eac4133df0&run_id=34643c8284394131854467eac4133df0]
[2025-03-01 15:32:47,851:WARNING:connectionpool:Retrying (Retry(total=2, connect=2, read=7, redirect=7, status=7)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f892c5b0c20>: Failed to resolve 'dagshub.com' ([Errno -3] Temporary failure in name resolution)")': /RymTangour/Kideny_Disease_Classification.mlflow/api/2.0/mlflow/runs/get?run_uuid=34643c8284394131854467eac4133df0&run_id=34643c8284394131854467eac4133df0]
[2025-03-01 15:34:02,832:WARNING:connectionpool:Retrying (Retry(total=1, connect=1, read=7, redirect=7, status=7)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f892c5b0e00>: Failed to resolve 'dagshub.com' ([Errno -3] Temporary failure in name resolution)")': /RymTangour/Kideny_Disease_Classification.mlflow/api/2.0/mlflow/runs/get?run_uuid=34643c8284394131854467eac4133df0&run_id=34643c8284394131854467eac4133df0]
[2025-03-01 16:24:13,349:INFO:main: stage Data Ingestion stage  started]
[2025-03-01 16:24:13,352:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-01 16:24:13,355:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-01 16:24:13,356:INFO:common:created directory at: artifacts]
[2025-03-01 16:24:13,362:INFO:common:created directory at: artifacts/data_ingestion]
[2025-03-01 16:24:13,366:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-02 22:54:03,836:INFO:main: stage Data Ingestion stage  started]
[2025-03-02 22:54:03,846:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-02 22:54:03,873:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-02 22:54:03,877:INFO:common:created directory at: artifacts]
[2025-03-02 22:54:03,884:INFO:common:created directory at: artifacts/data_ingestion]
[2025-03-02 22:54:03,891:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-02 22:54:49,461:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-02 22:54:57,979:INFO:main:Stage Data Ingestion stage completed]
[2025-03-02 22:54:57,979:INFO:main: stage Prepare base model  started]
[2025-03-02 22:54:57,984:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-02 22:54:57,989:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-02 22:54:57,993:INFO:common:created directory at: artifacts]
[2025-03-02 22:54:57,996:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-03-02 22:55:09,580:INFO:main:Stage Prepare base model completed]
[2025-03-02 22:55:09,580:INFO:main: stage Training  started]
[2025-03-02 22:55:09,584:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-02 22:55:09,589:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-02 22:55:09,591:INFO:common:created directory at: artifacts]
[2025-03-02 22:55:09,592:INFO:common:created directory at: artifacts/training]
[2025-03-02 22:56:30,517:INFO:main:Stage Training completed]
[2025-03-02 22:56:30,517:INFO:main: stage Evaluation stage  started]
[2025-03-02 22:56:30,526:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-02 22:56:30,537:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-02 22:56:30,548:INFO:common:created directory at: artifacts]
[2025-03-02 22:56:34,091:INFO:common:json file saved at:scores.json]
[2025-03-02 22:56:34,515:INFO:_client:HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-03-02 22:56:34,522:INFO:helpers:Accessing as RymTangour]
[2025-03-02 22:56:34,888:INFO:_client:HTTP Request: GET https://dagshub.com/api/v1/repos/RymTangour/Kideny_Disease_Classification "HTTP/1.1 200 OK"]
[2025-03-02 22:56:35,163:INFO:_client:HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-03-02 22:56:35,165:INFO:helpers:Initialized MLflow to track repo "RymTangour/Kideny_Disease_Classification"]
[2025-03-02 22:56:35,166:INFO:helpers:Repository RymTangour/Kideny_Disease_Classification initialized!]
[2025-03-02 23:22:58,691:INFO:stage_01_data_Ingestion:stage Data Ingestion stage started*]
[2025-03-02 23:22:58,706:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-02 23:22:58,721:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-02 23:22:58,730:INFO:common:created directory at: artifacts]
[2025-03-02 23:22:58,732:INFO:common:created directory at: artifacts/data_ingestion]
[2025-03-02 23:22:58,734:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-02 23:24:02,091:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-02 23:24:11,396:INFO:stage_01_data_Ingestion: stage Data Ingestion stage completed]
[2025-03-02 23:26:57,865:INFO:stage_02_prepare_base_model: stage Prepare base model  started]
[2025-03-02 23:26:57,875:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-02 23:26:57,882:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-02 23:26:57,886:INFO:common:created directory at: artifacts]
[2025-03-02 23:26:57,895:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-03-02 23:27:09,102:INFO:stage_02_prepare_base_model:Stage Prepare base model completed]
[2025-03-02 23:28:27,926:INFO:stage_03_model_training: stage Training  started]
[2025-03-02 23:28:27,933:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-02 23:28:27,940:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-02 23:28:27,944:INFO:common:created directory at: artifacts]
[2025-03-02 23:28:27,948:INFO:common:created directory at: artifacts/training]
[2025-03-02 23:30:03,176:INFO:stage_03_model_training:Stage Training completed]
[2025-03-02 23:31:38,690:INFO:stage_04_model_evaluation: stage Evaluation stage  started]
[2025-03-02 23:31:38,694:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-02 23:31:38,697:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-02 23:31:38,699:INFO:common:created directory at: artifacts]
[2025-03-02 23:32:01,563:INFO:common:json file saved at:scores.json]
[2025-03-02 23:32:01,586:INFO:common:json file saved at:scores.json]
[2025-03-02 23:32:01,587:INFO:stage_04_model_evaluation:Stage Evaluation stage completed]
[2025-03-02 23:36:57,799:INFO:stage_04_model_evaluation: stage Evaluation stage  started]
[2025-03-02 23:36:57,804:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-02 23:36:57,807:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-02 23:36:57,809:INFO:common:created directory at: artifacts]
[2025-03-02 23:37:19,490:INFO:common:json file saved at:scores.json]
[2025-03-02 23:37:19,526:INFO:common:json file saved at:scores.json]
[2025-03-02 23:37:20,214:INFO:_client:HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-03-02 23:37:20,229:INFO:helpers:Accessing as RymTangour]
[2025-03-02 23:37:20,653:INFO:_client:HTTP Request: GET https://dagshub.com/api/v1/repos/RymTangour/Kideny_Disease_Classification "HTTP/1.1 200 OK"]
[2025-03-02 23:37:20,916:INFO:_client:HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-03-02 23:37:20,920:INFO:helpers:Initialized MLflow to track repo "RymTangour/Kideny_Disease_Classification"]
[2025-03-02 23:37:20,923:INFO:helpers:Repository RymTangour/Kideny_Disease_Classification initialized!]
[2025-03-03 00:37:36,582:INFO:_internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.28.247.219:8080]
[2025-03-03 00:37:36,584:INFO:_internal:[33mPress CTRL+C to quit[0m]
[2025-03-03 00:37:40,151:INFO:_internal:127.0.0.1 - - [03/Mar/2025 00:37:40] "GET / HTTP/1.1" 200 -]
[2025-03-03 00:38:00,453:ERROR:app:Exception on /predict [POST]]
Traceback (most recent call last):
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask_cors/decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/src/cnnClassifier/pipeline/prediction.py", line 15, in predict
    model =load_model(os.path.join("model","model.keras"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/keras/src/saving/saving_api.py", line 200, in load_model
    raise ValueError(
ValueError: File not found: filepath=model/model.keras. Please ensure the file is an accessible `.keras` zip file.
[2025-03-03 00:38:00,575:INFO:_internal:127.0.0.1 - - [03/Mar/2025 00:38:00] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-03 00:45:15,171:INFO:_internal:127.0.0.1 - - [03/Mar/2025 00:45:15] "GET / HTTP/1.1" 200 -]
[2025-03-03 00:45:19,245:INFO:_internal:127.0.0.1 - - [03/Mar/2025 00:45:19] "GET / HTTP/1.1" 200 -]
[2025-03-03 00:49:19,916:INFO:_internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.28.247.219:8080]
[2025-03-03 00:49:19,917:INFO:_internal:[33mPress CTRL+C to quit[0m]
[2025-03-03 00:49:24,655:INFO:_internal:127.0.0.1 - - [03/Mar/2025 00:49:24] "GET / HTTP/1.1" 200 -]
[2025-03-03 00:49:24,729:INFO:_internal:127.0.0.1 - - [03/Mar/2025 00:49:24] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-03-03 00:54:28,149:INFO:_internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.28.247.219:8080]
[2025-03-03 00:54:28,151:INFO:_internal:[33mPress CTRL+C to quit[0m]
[2025-03-03 00:54:34,874:INFO:_internal:127.0.0.1 - - [03/Mar/2025 00:54:34] "GET / HTTP/1.1" 200 -]
[2025-03-03 00:54:46,379:ERROR:app:Exception on /predict [POST]]
Traceback (most recent call last):
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask_cors/decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/src/cnnClassifier/pipeline/prediction.py", line 15, in predict
    model =load_model(os.path.join("model","model.keras"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/keras/src/saving/saving_api.py", line 200, in load_model
    raise ValueError(
ValueError: File not found: filepath=model/model.keras. Please ensure the file is an accessible `.keras` zip file.
[2025-03-03 00:54:46,475:INFO:_internal:127.0.0.1 - - [03/Mar/2025 00:54:46] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-03 01:02:38,355:INFO:_internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.28.247.219:8080]
[2025-03-03 01:02:38,356:INFO:_internal:[33mPress CTRL+C to quit[0m]
[2025-03-03 01:02:47,121:INFO:_internal:127.0.0.1 - - [03/Mar/2025 01:02:47] "GET / HTTP/1.1" 200 -]
[2025-03-03 01:03:26,088:ERROR:app:Exception on /predict [POST]]
Traceback (most recent call last):
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask_cors/decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/src/cnnClassifier/pipeline/prediction.py", line 21, in predict
    result=np.argmax(model.predict(test_image), axis=1)#When you call model.predict(test_image), the model outputs a probability distribution over the classes.[[0.2, 0.8]]The np.argmax function is used to find the index of the maximum value in the output array.
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/keras/src/layers/input_spec.py", line 245, in assert_input_compatibility
    raise ValueError(
ValueError: Input 0 of layer "functional" is incompatible with the layer: expected shape=(None, 224, 224, 3), found shape=(1, 244, 244, 3)
[2025-03-03 01:03:26,398:INFO:_internal:127.0.0.1 - - [03/Mar/2025 01:03:26] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-03 01:08:43,668:INFO:_internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.28.247.219:8080]
[2025-03-03 01:08:43,668:INFO:_internal:[33mPress CTRL+C to quit[0m]
[2025-03-03 01:08:47,931:INFO:_internal:127.0.0.1 - - [03/Mar/2025 01:08:47] "GET / HTTP/1.1" 200 -]
[2025-03-03 01:09:10,820:INFO:_internal:127.0.0.1 - - [03/Mar/2025 01:09:10] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 03:55:29,166:INFO:_internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.28.247.219:8080]
[2025-03-03 03:55:29,169:INFO:_internal:[33mPress CTRL+C to quit[0m]
[2025-03-03 03:55:33,464:INFO:_internal:127.0.0.1 - - [03/Mar/2025 03:55:33] "GET / HTTP/1.1" 200 -]
[2025-03-03 03:55:33,568:INFO:_internal:127.0.0.1 - - [03/Mar/2025 03:55:33] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-03-03 04:02:31,008:INFO:_internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.28.247.219:8080]
[2025-03-03 04:02:31,010:INFO:_internal:[33mPress CTRL+C to quit[0m]
[2025-03-03 04:02:35,158:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:02:35] "GET / HTTP/1.1" 200 -]
[2025-03-03 04:02:56,171:ERROR:app:Exception on /predict [POST]]
Traceback (most recent call last):
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask_cors/decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/src/cnnClassifier/pipeline/prediction.py", line 18, in predict
    test_image=image.load_img(imagename, target_size=(224,224))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/keras/src/utils/image_utils.py", line 236, in load_img
    img = pil_image.open(io.BytesIO(f.read()))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f558836d4e0>
[2025-03-03 04:02:56,409:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:02:56] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-03 04:03:52,718:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:03:52] "GET / HTTP/1.1" 200 -]
[2025-03-03 04:03:55,237:ERROR:app:Exception on /predict [POST]]
Traceback (most recent call last):
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/flask_cors/decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/src/cnnClassifier/pipeline/prediction.py", line 18, in predict
    test_image=image.load_img(imagename, target_size=(224,224))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/keras/src/utils/image_utils.py", line 236, in load_img
    img = pil_image.open(io.BytesIO(f.read()))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f558836e8e0>
[2025-03-03 04:03:55,253:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:03:55] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-03 04:03:56,419:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:03:56] "GET / HTTP/1.1" 200 -]
[2025-03-03 04:04:18,882:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:04:18] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 04:12:38,073:INFO:_internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.28.247.219:8080]
[2025-03-03 04:12:38,074:INFO:_internal:[33mPress CTRL+C to quit[0m]
[2025-03-03 04:12:43,088:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:12:43] "GET / HTTP/1.1" 200 -]
[2025-03-03 04:13:14,528:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:13:14] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 04:13:33,289:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:13:33] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 04:13:41,056:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:13:41] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 04:13:46,905:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:13:46] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 04:13:55,380:WARNING:polymorphic_function:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7f04bffb6980> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-03-03 04:13:55,506:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:13:55] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 04:14:04,739:WARNING:polymorphic_function:6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7f04ceb2b380> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-03-03 04:14:04,866:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:14:04] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 04:23:55,394:INFO:_internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.28.247.219:8080]
[2025-03-03 04:23:55,404:INFO:_internal:[33mPress CTRL+C to quit[0m]
[2025-03-03 04:24:24,353:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:24:24] "GET / HTTP/1.1" 200 -]
[2025-03-03 04:24:30,386:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:24:30] "[31m[1mPOST /predict HTTP/1.1[0m" 415 -]
[2025-03-03 04:24:31,957:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:24:31] "[31m[1mPOST /predict HTTP/1.1[0m" 415 -]
[2025-03-03 04:24:33,533:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:24:33] "[31m[1mPOST /predict HTTP/1.1[0m" 415 -]
[2025-03-03 04:24:33,780:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:24:33] "[31m[1mPOST /predict HTTP/1.1[0m" 415 -]
[2025-03-03 04:24:35,242:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:24:35] "[31m[1mPOST /predict HTTP/1.1[0m" 415 -]
[2025-03-03 04:24:35,921:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:24:35] "[31m[1mPOST /predict HTTP/1.1[0m" 415 -]
[2025-03-03 04:24:36,338:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:24:36] "[31m[1mPOST /predict HTTP/1.1[0m" 415 -]
[2025-03-03 04:24:37,665:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:24:37] "[31m[1mPOST /predict HTTP/1.1[0m" 415 -]
[2025-03-03 04:24:37,910:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:24:37] "[31m[1mPOST /predict HTTP/1.1[0m" 415 -]
[2025-03-03 04:24:38,094:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:24:38] "[31m[1mPOST /predict HTTP/1.1[0m" 415 -]
[2025-03-03 04:24:38,372:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:24:38] "[31m[1mPOST /predict HTTP/1.1[0m" 415 -]
[2025-03-03 04:24:38,529:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:24:38] "[31m[1mPOST /predict HTTP/1.1[0m" 415 -]
[2025-03-03 04:26:37,144:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:26:37] "[31m[1mPOST /predict HTTP/1.1[0m" 415 -]
[2025-03-03 04:31:23,259:INFO:_internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.28.247.219:8080]
[2025-03-03 04:31:23,260:INFO:_internal:[33mPress CTRL+C to quit[0m]
[2025-03-03 04:32:52,040:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:32:52] "GET / HTTP/1.1" 200 -]
[2025-03-03 04:33:23,952:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:33:23] "GET / HTTP/1.1" 200 -]
[2025-03-03 04:36:01,690:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:36:01] "GET / HTTP/1.1" 200 -]
[2025-03-03 04:42:11,115:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:42:11] "GET / HTTP/1.1" 200 -]
[2025-03-03 04:50:22,560:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:50:22] "GET / HTTP/1.1" 200 -]
[2025-03-03 04:54:06,694:INFO:_internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.28.247.219:8080]
[2025-03-03 04:54:06,694:INFO:_internal:[33mPress CTRL+C to quit[0m]
[2025-03-03 04:58:20,876:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:58:20] "GET / HTTP/1.1" 200 -]
[2025-03-03 04:59:11,759:INFO:_internal:127.0.0.1 - - [03/Mar/2025 04:59:11] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 05:03:24,483:INFO:_internal:127.0.0.1 - - [03/Mar/2025 05:03:24] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 05:03:29,050:INFO:_internal:127.0.0.1 - - [03/Mar/2025 05:03:29] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 05:03:38,322:INFO:_internal:127.0.0.1 - - [03/Mar/2025 05:03:38] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 05:03:47,244:WARNING:polymorphic_function:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7fd697fa0b80> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-03-03 05:03:47,374:INFO:_internal:127.0.0.1 - - [03/Mar/2025 05:03:47] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 05:04:00,934:WARNING:polymorphic_function:6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7fd6a6617740> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-03-03 05:04:01,066:INFO:_internal:127.0.0.1 - - [03/Mar/2025 05:04:01] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 05:04:13,042:INFO:_internal:127.0.0.1 - - [03/Mar/2025 05:04:13] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 05:04:23,728:INFO:_internal:127.0.0.1 - - [03/Mar/2025 05:04:23] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 05:04:36,103:INFO:_internal:127.0.0.1 - - [03/Mar/2025 05:04:36] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 05:04:47,940:INFO:_internal:127.0.0.1 - - [03/Mar/2025 05:04:47] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 05:06:24,708:INFO:_internal:127.0.0.1 - - [03/Mar/2025 05:06:24] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 11:56:47,316:INFO:_internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.28.247.219:8080]
[2025-03-03 11:56:47,318:INFO:_internal:[33mPress CTRL+C to quit[0m]
[2025-03-03 11:57:44,018:INFO:_internal:127.0.0.1 - - [03/Mar/2025 11:57:44] "GET / HTTP/1.1" 200 -]
[2025-03-03 11:59:41,899:INFO:_internal:127.0.0.1 - - [03/Mar/2025 11:59:41] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 12:14:57,411:INFO:main: stage Data Ingestion stage  started]
[2025-03-03 12:14:57,464:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-03 12:14:57,477:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-03 12:14:57,522:INFO:common:created directory at: artifacts]
[2025-03-03 12:14:57,577:INFO:common:created directory at: artifacts/data_ingestion]
[2025-03-03 12:14:57,625:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-03 12:15:08,673:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1g0FAt3OgF4BOqwvxBEMCHJ04FaypAALz/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-03 12:15:23,377:INFO:main:Stage Data Ingestion stage completed]
[2025-03-03 12:15:23,378:INFO:main: stage Prepare base model  started]
[2025-03-03 12:15:23,392:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-03 12:15:23,446:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-03 12:15:23,475:INFO:common:created directory at: artifacts]
[2025-03-03 12:15:23,499:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-03-03 12:15:34,605:INFO:main:Stage Prepare base model completed]
[2025-03-03 12:15:34,605:INFO:main: stage Training  started]
[2025-03-03 12:15:34,608:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-03 12:15:34,610:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-03 12:15:34,611:INFO:common:created directory at: artifacts]
[2025-03-03 12:15:34,625:INFO:common:created directory at: artifacts/training]
[2025-03-03 12:16:12,035:INFO:main:Stage Training completed]
[2025-03-03 12:16:12,037:INFO:main: stage Evaluation stage  started]
[2025-03-03 12:16:12,051:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-03 12:16:12,064:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-03 12:16:12,067:INFO:common:created directory at: artifacts]
[2025-03-03 12:16:16,124:INFO:common:json file saved at:scores.json]
[2025-03-03 12:16:16,161:INFO:common:json file saved at:scores.json]
[2025-03-03 12:16:16,162:INFO:main:Stage Evaluation stage completed]
[2025-03-03 12:34:50,643:INFO:main: stage Data Ingestion stage  started]
[2025-03-03 12:34:50,646:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-03 12:34:50,649:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-03 12:34:50,657:INFO:common:created directory at: artifacts]
[2025-03-03 12:34:50,661:INFO:common:created directory at: artifacts/data_ingestion]
[2025-03-03 12:34:50,663:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1LaOaSmJyoYyh9I-sfFnTGSlQq7EsrEwT/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-03 12:34:51,567:ERROR:main:Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1LaOaSmJyoYyh9I-sfFnTGSlQq7EsrEwT

but Gdown can't. Please check connections and permissions.]
Traceback (most recent call last):
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/gdown/download.py", line 267, in download
    url = get_url_from_gdrive_confirmation(res.text)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/gdown/download.py", line 55, in get_url_from_gdrive_confirmation
    raise FileURLRetrievalError(
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses. Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/projet/Kideny_Disease_Classification/main.py", line 13, in <module>
    obj.main()
  File "/mnt/c/projet/Kideny_Disease_Classification/src/cnnClassifier/pipeline/stage_01_data_Ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/mnt/c/projet/Kideny_Disease_Classification/src/cnnClassifier/components/data_ingestion.py", line 27, in download_file
    raise e
  File "/mnt/c/projet/Kideny_Disease_Classification/src/cnnClassifier/components/data_ingestion.py", line 22, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "/mnt/c/projet/Kideny_Disease_Classification/myenv/lib/python3.12/site-packages/gdown/download.py", line 278, in download
    raise FileURLRetrievalError(message)
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1LaOaSmJyoYyh9I-sfFnTGSlQq7EsrEwT

but Gdown can't. Please check connections and permissions.
[2025-03-03 12:36:21,744:INFO:main: stage Data Ingestion stage  started]
[2025-03-03 12:36:21,752:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-03 12:36:21,775:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-03 12:36:21,787:INFO:common:created directory at: artifacts]
[2025-03-03 12:36:21,794:INFO:common:created directory at: artifacts/data_ingestion]
[2025-03-03 12:36:21,802:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1LaOaSmJyoYyh9I-sfFnTGSlQq7EsrEwT/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-03 12:38:28,469:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1LaOaSmJyoYyh9I-sfFnTGSlQq7EsrEwT/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-03 12:41:33,598:INFO:main:Stage Data Ingestion stage completed]
[2025-03-03 12:41:33,601:INFO:main: stage Prepare base model  started]
[2025-03-03 12:41:33,625:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-03 12:41:33,647:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-03 12:41:33,652:INFO:common:created directory at: artifacts]
[2025-03-03 12:41:33,659:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-03-03 12:41:44,508:INFO:main:Stage Prepare base model completed]
[2025-03-03 12:41:44,508:INFO:main: stage Training  started]
[2025-03-03 12:41:44,511:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-03 12:41:44,513:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-03 12:41:44,515:INFO:common:created directory at: artifacts]
[2025-03-03 12:41:44,520:INFO:common:created directory at: artifacts/training]
[2025-03-03 12:52:49,977:INFO:stage_01_data_Ingestion:stage Data Ingestion stage started*]
[2025-03-03 12:52:49,979:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-03 12:52:49,981:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-03 12:52:49,982:INFO:common:created directory at: artifacts]
[2025-03-03 12:52:49,984:INFO:common:created directory at: artifacts/data_ingestion]
[2025-03-03 12:52:49,985:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1LaOaSmJyoYyh9I-sfFnTGSlQq7EsrEwT/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-03 12:54:57,209:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1LaOaSmJyoYyh9I-sfFnTGSlQq7EsrEwT/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-03 12:58:36,559:INFO:stage_01_data_Ingestion: stage Data Ingestion stage completed]
[2025-03-03 13:04:15,585:INFO:stage_01_data_Ingestion:stage Data Ingestion stage started*]
[2025-03-03 13:04:15,602:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-03 13:04:15,605:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-03 13:04:15,608:INFO:common:created directory at: artifacts]
[2025-03-03 13:04:15,611:INFO:common:created directory at: artifacts/data_ingestion]
[2025-03-03 13:04:15,612:INFO:data_ingestion:Downloading data from hhttps://drive.google.com/file/d/1LaOaSmJyoYyh9I-sfFnTGSlQq7EsrEwT/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-03 13:06:21,924:INFO:data_ingestion:Download data from hhttps://drive.google.com/file/d/1LaOaSmJyoYyh9I-sfFnTGSlQq7EsrEwT/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-03 13:09:30,956:INFO:stage_01_data_Ingestion: stage Data Ingestion stage completed]
[2025-03-03 14:29:54,619:INFO:stage_01_data_Ingestion:stage Data Ingestion stage started*]
[2025-03-03 14:29:54,623:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-03 14:29:54,625:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-03 14:29:54,626:INFO:common:created directory at: artifacts]
[2025-03-03 14:29:54,637:INFO:common:created directory at: artifacts/data_ingestion]
[2025-03-03 14:29:54,642:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1LaOaSmJyoYyh9I-sfFnTGSlQq7EsrEwT/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-03 14:32:01,272:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1LaOaSmJyoYyh9I-sfFnTGSlQq7EsrEwT/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-03 14:35:30,494:INFO:stage_01_data_Ingestion: stage Data Ingestion stage completed]
[2025-03-03 14:48:26,773:INFO:stage_01_data_Ingestion:stage Data Ingestion stage started*]
[2025-03-03 14:48:26,776:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-03 14:48:26,778:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-03 14:48:26,779:INFO:common:created directory at: artifacts]
[2025-03-03 14:48:26,788:INFO:common:created directory at: artifacts/data_ingestion]
[2025-03-03 14:48:26,790:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1LaOaSmJyoYyh9I-sfFnTGSlQq7EsrEwT/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-03 14:50:37,438:INFO:data_ingestion:Download data from https://drive.google.com/file/d/1LaOaSmJyoYyh9I-sfFnTGSlQq7EsrEwT/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-03 14:53:46,341:INFO:stage_01_data_Ingestion: stage Data Ingestion stage completed]
[2025-03-03 15:11:16,378:INFO:stage_02_prepare_base_model: stage Prepare base model  started]
[2025-03-03 15:11:16,381:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-03 15:11:16,383:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-03 15:11:16,384:INFO:common:created directory at: artifacts]
[2025-03-03 15:11:16,388:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-03-03 15:11:29,794:INFO:stage_02_prepare_base_model:Stage Prepare base model completed]
[2025-03-03 15:20:56,223:INFO:stage_03_model_training: stage Training  started]
[2025-03-03 15:20:56,226:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-03 15:20:56,228:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-03 15:20:56,229:INFO:common:created directory at: artifacts]
[2025-03-03 15:20:56,231:INFO:common:created directory at: artifacts/training]
[2025-03-03 15:30:24,170:INFO:stage_03_model_training: stage Training  started]
[2025-03-03 15:30:24,173:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-03 15:30:24,175:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-03 15:30:24,176:INFO:common:created directory at: artifacts]
[2025-03-03 15:30:24,179:INFO:common:created directory at: artifacts/training]
[2025-03-03 15:36:11,549:INFO:stage_03_model_training: stage Training  started]
[2025-03-03 15:36:11,552:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-03 15:36:11,556:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-03 15:36:11,558:INFO:common:created directory at: artifacts]
[2025-03-03 15:36:11,569:INFO:common:created directory at: artifacts/training]
[2025-03-03 15:39:19,264:INFO:stage_03_model_training:Stage Training completed]
[2025-03-03 15:45:13,482:INFO:stage_04_model_evaluation: stage Evaluation stage  started]
[2025-03-03 15:45:13,486:INFO:common:yaml file :config/config.yaml loaded succfully]
[2025-03-03 15:45:13,490:INFO:common:yaml file :params.yaml loaded succfully]
[2025-03-03 15:45:13,491:INFO:common:created directory at: artifacts]
[2025-03-03 15:45:55,620:INFO:common:json file saved at:scores.json]
[2025-03-03 15:45:55,650:INFO:common:json file saved at:scores.json]
[2025-03-03 15:45:55,651:INFO:stage_04_model_evaluation:Stage Evaluation stage completed]
[2025-03-03 15:53:09,339:INFO:_internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.28.247.219:8080]
[2025-03-03 15:53:09,340:INFO:_internal:[33mPress CTRL+C to quit[0m]
[2025-03-03 15:53:13,957:INFO:_internal:127.0.0.1 - - [03/Mar/2025 15:53:13] "GET / HTTP/1.1" 200 -]
[2025-03-03 15:53:42,389:INFO:_internal:127.0.0.1 - - [03/Mar/2025 15:53:42] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 15:55:34,307:INFO:_internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.28.247.219:8080]
[2025-03-03 15:55:34,308:INFO:_internal:[33mPress CTRL+C to quit[0m]
[2025-03-03 15:55:38,238:INFO:_internal:127.0.0.1 - - [03/Mar/2025 15:55:38] "GET / HTTP/1.1" 200 -]
[2025-03-03 15:55:38,330:INFO:_internal:127.0.0.1 - - [03/Mar/2025 15:55:38] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-03-03 15:56:04,180:INFO:_internal:127.0.0.1 - - [03/Mar/2025 15:56:04] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 15:56:29,268:INFO:_internal:127.0.0.1 - - [03/Mar/2025 15:56:29] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 15:56:32,373:INFO:_internal:127.0.0.1 - - [03/Mar/2025 15:56:32] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 15:56:41,492:INFO:_internal:127.0.0.1 - - [03/Mar/2025 15:56:41] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 15:56:56,414:WARNING:polymorphic_function:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7f040a1ec220> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-03-03 15:56:56,538:INFO:_internal:127.0.0.1 - - [03/Mar/2025 15:56:56] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 15:56:58,491:INFO:_internal:127.0.0.1 - - [03/Mar/2025 15:56:58] "GET / HTTP/1.1" 200 -]
[2025-03-03 16:04:48,883:INFO:_internal:127.0.0.1 - - [03/Mar/2025 16:04:48] "GET / HTTP/1.1" 200 -]
[2025-03-03 16:17:31,536:INFO:_internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.28.247.219:8080]
[2025-03-03 16:17:31,536:INFO:_internal:[33mPress CTRL+C to quit[0m]
[2025-03-03 16:18:40,000:INFO:_internal:127.0.0.1 - - [03/Mar/2025 16:18:40] "GET / HTTP/1.1" 200 -]
[2025-03-03 16:18:42,085:INFO:_internal:127.0.0.1 - - [03/Mar/2025 16:18:42] "GET / HTTP/1.1" 200 -]
[2025-03-03 16:22:14,604:INFO:_internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.28.247.219:8080]
[2025-03-03 16:22:14,608:INFO:_internal:[33mPress CTRL+C to quit[0m]
[2025-03-03 16:24:31,090:INFO:_internal:127.0.0.1 - - [03/Mar/2025 16:24:31] "GET / HTTP/1.1" 200 -]
[2025-03-03 16:24:37,168:INFO:_internal:127.0.0.1 - - [03/Mar/2025 16:24:37] "GET / HTTP/1.1" 200 -]
[2025-03-03 16:25:03,107:INFO:_internal:127.0.0.1 - - [03/Mar/2025 16:25:03] "POST /predict HTTP/1.1" 200 -]
[2025-03-03 16:26:35,361:INFO:_internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.28.247.219:8080]
[2025-03-03 16:26:35,361:INFO:_internal:[33mPress CTRL+C to quit[0m]
[2025-03-03 16:27:22,460:INFO:_internal:127.0.0.1 - - [03/Mar/2025 16:27:22] "GET / HTTP/1.1" 200 -]
[2025-03-03 16:27:26,749:INFO:_internal:127.0.0.1 - - [03/Mar/2025 16:27:26] "GET / HTTP/1.1" 200 -]
[2025-03-03 16:34:32,901:INFO:_internal:127.0.0.1 - - [03/Mar/2025 16:34:32] "GET / HTTP/1.1" 200 -]
[2025-03-03 16:34:33,707:INFO:_internal:127.0.0.1 - - [03/Mar/2025 16:34:33] "GET / HTTP/1.1" 200 -]
[2025-03-03 16:35:18,304:INFO:_internal:127.0.0.1 - - [03/Mar/2025 16:35:18] "POST /predict HTTP/1.1" 200 -]
